/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_e9ab98e991ab_voice_SoundTypeFix */

#ifndef _Included_com_e9ab98e991ab_voice_SoundTypeFix
#define _Included_com_e9ab98e991ab_voice_SoundTypeFix
#ifdef __cplusplus
extern "C" {
#endif
#undef com_e9ab98e991ab_voice_SoundTypeFix_MODE_NORMAL
#define com_e9ab98e991ab_voice_SoundTypeFix_MODE_NORMAL 0L
#undef com_e9ab98e991ab_voice_SoundTypeFix_MODE_LUOLI
#define com_e9ab98e991ab_voice_SoundTypeFix_MODE_LUOLI 1L
#undef com_e9ab98e991ab_voice_SoundTypeFix_MODE_DASHU
#define com_e9ab98e991ab_voice_SoundTypeFix_MODE_DASHU 2L
#undef com_e9ab98e991ab_voice_SoundTypeFix_MODE_JINGSONG
#define com_e9ab98e991ab_voice_SoundTypeFix_MODE_JINGSONG 3L
#undef com_e9ab98e991ab_voice_SoundTypeFix_MODE_GAOGUAI
#define com_e9ab98e991ab_voice_SoundTypeFix_MODE_GAOGUAI 4L
#undef com_e9ab98e991ab_voice_SoundTypeFix_MODE_KONGLING
#define com_e9ab98e991ab_voice_SoundTypeFix_MODE_KONGLING 5L
/*
 * Class:     com_e9ab98e991ab_voice_SoundTypeFix
 * Method:    fix
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_e9ab98e991ab_voice_SoundTypeFix_fix
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
